server:
  port: 8001
spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    host: 127.0.0.1
    listener:
      concurrency: 10
      max-concurrency: 20
      prefetch: 5
    password: guest
    port: 5672
    username: guest
